apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: whiteboard-statefulset
spec:
  serviceName: "whiteboard"
  replicas: 2
  selector:
    matchLabels:
      app: whiteboard
  template:
    metadata:
      labels:
        app: whiteboard
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - eu-west-2a
                - eu-west-2b
                - eu-west-2c
      containers:
      - name: whiteboard
        image: public.ecr.aws/x2e6c2d3/icc-whiteboard:latest
        ports:
        - containerPort: 8080
          name: whiteboard
        volumeMounts:
        - name: savedboards
          mountPath: /opt/app/savedBoards
      volumes:
      - name: savedboards
        persistentVolumeClaim:
        claimName: savedboards
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: savedboards
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: whiteboard-service
spec:
  type: NodePort
  selector:
    app: whiteboard
  ports:
  - nodePort: 30000
    port: 8080
    protocol: TCP
    targetPort: 8080

---
piVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: whiteboard-hpa
  namespace: whiteboard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: statefulSet
    name: whiteboard-statefulset
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50